# Generated by Django 4.1 on 2022-08-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Clients",),
    ]
