# Generated by Django 4.1 on 2022-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0008_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                ("icon_name", models.CharField(max_length=50)),
            ],
        ),
    ]
