# Generated by Django 4.1 on 2022-08-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0011_rename_username_clients_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=255)),
                ("shipping_address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subtotal", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Order Received", "Order Received"),
                            ("Order Processing", "Order Processing"),
                            ("Order On The Way", "Order On The Way"),
                            ("Order Delivered", "Order Delivered"),
                            ("Order Cancelled", "Order Cancelled"),
                        ],
                        default="Order Received",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash On Delivery", "Cash On Delivery"),
                            ("Master Card", "Master Card"),
                            ("Visa Card", "Visa Card"),
                            ("Paypal", "Paypal"),
                            ("Fawry", "Fawry"),
                        ],
                        default="Cash On Delivery",
                        max_length=50,
                    ),
                ),
                (
                    "payment_completed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ecommerce.cart"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecommerce.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                    ),
                ),
            ],
        ),
    ]
