# Generated by Django 4.1 on 2022-08-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0013_product_description_ar_product_policy_return_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="policy_return",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="policy_return_ar",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_ar",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="warnty",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="warnty_ar",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
